# Generated by Django 3.2.9 on 2021-12-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(default=1980.0, on_delete=django.db.models.deletion.CASCADE, to='servicios.categoriaservicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.FloatField(default=1980),
            preserve_default=False,
        ),
    ]
