# Generated by Django 3.2.9 on 2021-12-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_contenidopost_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidopost',
            name='cuerpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='blog.post'),
        ),
    ]
