# Generated by Django 3.2.9 on 2021-12-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_contenidopost_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.TextField(default=1980),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContenidoPost',
        ),
    ]
