# Generated by Django 3.2.9 on 2021-12-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211201_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriapost',
            name='creado',
        ),
    ]
