# Generated by Django 3.2.9 on 2021-12-01 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_categoriapost_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriapost',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriapost',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriapost',
            name='nombre',
            field=models.CharField(default=1980, max_length=50),
            preserve_default=False,
        ),
    ]
