# Generated by Django 3.2.9 on 2021-12-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211201_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.CharField(default=1980, max_length=250),
            preserve_default=False,
        ),
    ]
