# Generated by Django 3.2.9 on 2021-12-02 04:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
